# -*- coding: utf-8 -*-
"""PraktikumSesi2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrXJnabV9qigU9lkKnwNTT0K_yxWNjPD
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Dataset_Kinerja_Karyawan.csv')
df.info()

df.head()

print("=== Statistika Deskriptif Skor Kinerja ===")
desc_stats = df['Skor_Kinerja'].describe()
print(desc_stats)

modus = df['Skor_Kinerja'].mode()[0]
varians = df['Skor_Kinerja'].var()
range_skor = df['Skor_Kinerja'].max() - df['Skor_Kinerja'].min()

print(f"\nModus: {modus}")
print(f"Varians: {varians:.2f}")
print(f"Range: {range_skor}")

plt.figure(figsize=(10, 6))
sns.histplot(df['Skor_Kinerja'], bins=20, kde=True, color='skyblue', edgecolor='black')
plt.axvline(df['Skor_Kinerja'].mean(), color='red', linestyle='dashed', linewidth=2, label=f"Mean: {df['Skor_Kinerja'].mean():.2f}")
plt.axvline(df['Skor_Kinerja'].median(), color='green', linestyle='dashed', linewidth=2, label=f"Median: {df['Skor_Kinerja'].median():.2f}")
plt.title('Distribusi Skor Kinerja Karyawan', fontsize=14, pad=15)
plt.xlabel('Skor Kinerja', fontsize=12)
plt.ylabel('Frekuensi', fontsize=12)
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Departemen', y='Skor_Kinerja', data=df, palette='Set2')
plt.title('Sebaran Skor Kinerja per Departemen', fontsize=14, pad=15)
plt.xlabel('Departemen', fontsize=12)
plt.ylabel('Skor Kinerja', fontsize=12)
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(x='Departemen', y='Lama_Bekerja_Tahun', data=df, errorbar=None, palette='viridis')
plt.title('Rata-rata Lama Bekerja Karyawan per Departemen', fontsize=14, pad=15)
plt.xlabel('Departemen', fontsize=12)
plt.ylabel('Lama Bekerja (Tahun)', fontsize=12)
plt.show()

"""Insight Bisnis Kinerja Karyawan

1. Kinerja karyawan secara umum cukup baik.
Rata-rata skor 68,36, median 69, dan modus 70. Angkanya hampir sama, jadi sebaran skornya seimbang (bentuk lonceng). Mayoritas karyawan ada di kisaran skor 60-77.

2. Kinerja antar departemen relatif merata.
Rata-rata skor semua departemen mirip (sekitar 66-69). HR paling tinggi (69,02) dan Operasional paling rendah (66,63), tapi selisihnya kecil. Operasional tetap perlu diperhatikan lebih lanjut.

3. Lama bekerja tidak menentukan kinerja.
Masa kerja paling panjang ada di Sales (8,08 tahun) dan paling pendek di HR (6,87 tahun), tapi skor kinerjanya tidak berbeda jauh. Jadi karyawan senior belum tentu berkinerja lebih baik, dan pelatihan skill tetap penting untuk semua karyawan.
"""